name: Setup SSH and RDP

on: [push, workflow_dispatch]

jobs:
  setup:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install SSH Server
      run: |
        # Install the OpenSSH server feature
        Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
        
        # Start the SSH server service
        Start-Service sshd
        
        # Set SSH server service to start automatically
        Set-Service -Name sshd -StartupType 'Automatic'
        
        # Configure the firewall for SSH
        Enable-NetFirewallRule -Name sshd

    - name: Enable Remote Desktop
      run: |
        $ErrorActionPreference = "Stop"
        # Enable Remote Desktop
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
        # Enable Network Level Authentication
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name 'UserAuthentication' -Value 1

    - name: Configure Firewall for RDP
      run: |
        # Allow RDP through the firewall
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Set Local User Password
      run: |
        # Set password for the 'runneradmin' user
        $securePassword = ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force
        Set-LocalUser -Name "runneradmin" -Password $securePassword

    - name: Print Public IP Address
      run: |
        # Get the public IP address
        $publicIP = Invoke-RestMethod -Uri "http://api.ipify.org?format=json"
        Write-Output "Public IP Address: $($publicIP.ip)"
